local M = {}
M.base_30 = {
  white = "#D5CCBA", -- Inverted: light text on dark bg
  darker_black = "#1a1410", -- Darkest background
  black = "#1C1612", -- Main dark background
  black2 = "#362b22", -- Secondary background (slightly lighter)
  one_bg = "#362b22", -- Background for floating windows
  one_bg2 = "#3c312a", -- Background for certain UI elements
  one_bg3 = "#4c4133", -- Background for other UI elements
  grey = "#60564a", -- Comments
  grey_fg = "#706658", -- Foreground grey (inactive text)
  light_grey = "#807668", -- Lighter grey for subtle text
  red = "#d85c4d", -- Error messages, deletions
  baby_pink = "#d89078", -- Lighter pink accent
  pink = "#cf8860", -- Pink accent color
  line = "#362b22", -- Line numbers background, vertical split lines
  green = "#d89669", -- Insert mode indicator (orange instead of green)
  vibrant_green = "#e9a678", -- Brighter orange accent
  blue = "#9f7f65", -- Normal mode indicator, info messages
  yellow = "#cf9c75", -- Visual mode indicator, warnings
  sun = "#e9c396", -- Brighter yellow accent
  purple = "#b88960", -- Purple accent, certain keywords
  orange = "#c89669", -- Orange accent, numbers
  cyan = "#9f7f65", -- Cyan accent, special characters
  statusline_bg = "#C3BAA8", -- Status line background
  lightbg = "#8E7F6F", -- Light background for certain UI elements
  pmenu_bg = "#b88960", -- Popup menu background
  folder_bg = "#9f7f65", -- Folder icons in file explorer
}
M.base_16 = {
  base00 = "#1C1612", -- Default dark background
  base01 = "#2a1f18", -- Lighter background (used for status bars, line numbers)
  base02 = "#4c4133", -- Selection background
  base03 = "#d87c6c", -- Comments, invisibles, line highlighting
  base04 = "#9f8f82", -- Dark foreground (used for line numbers, secondary text)
  base05 = "#c3baa8", -- Default foreground, caret, delimiters, operators
  base06 = "#c19b76", -- Light foreground
  base07 = "#c9c0ae", -- Lightest foreground
  base08 = "#db6657", -- Variables, XML tags, markup link text, markup lists, diff deleted
  base09 = "#b88960", -- Orange (numbers)
  base0A = "#d89371", -- Yellow (classes)
  base0B = "#d8864a", -- Orange (strings - replaced green)
  base0C = "#9f8f82", -- Cyan (support)
  base0D = "#6298b0", -- Blue (functions)
  base0E = "#9f8f82", -- Purple (keywords)
  base0F = "#9A4235", -- commas, brackets etc
}
M.type = "dark"
M.polish_hl = {}
return M
