local M = {}
M.base_30 = {
  white = "#F0BB90", -- Inverted: light text on dark bg
  darker_black = "#1a1410", -- Darkest background
  black = "#1C1612", -- Main dark background
  black2 = "#362b22", -- Secondary background (slightly lighter)
  one_bg = "#362b22", -- Background for floating windows
  one_bg2 = "#3c312a", -- Background for certain UI elements
  one_bg3 = "#4c4133", -- Background for other UI elements
  grey = "#756148", -- Line nums
  grey_fg = "#8a745c", -- (inactive text) < actually comments
  light_grey = "#807668", -- Lighter grey for subtle text
  red = "#6e241b", -- Error messages, deletions
  baby_pink = "#d89078", -- Lighter pink accent
  pink = "#cf8860", -- Pink accent color
  line = "#362b22", -- Line numbers background, vertical split lines
  green = "#C47C4F", -- Insert mode indicator (orange instead of green)
  vibrant_green = "#e9a678", -- Brighter orange accent
  blue = "#9f7f65", -- Normal mode indicator, info messages
  yellow = "#cf9c75", -- Visual mode indicator, warnings
  sun = "#e9c396", -- Brighter yellow accent
  purple = "#b88960", -- Purple accent, certain keywords
  orange = "#c89669", -- Orange accent, numbers
  cyan = "#9f7f65", -- Cyan accent, special characters
  statusline_bg = "#7a5845",
  lightbg = "#3D2E21",
  pmenu_bg = "#8f5b3c",  -- Darker
  folder_bg = "#5a3a25",  -- Darker
}
M.base_16 = {
  base00 = "#1C1612", -- Default dark background
  base01 = "#F5DCC6", -- Lighter background (used for status bars, line numbers)
  base02 = "#4c4133", -- Selection background
  base03 = "#d87c6c", -- Comments, invisibles, line highlighting
  base04 = "#9f8f82", -- Dark foreground (used for line numbers, secondary text)
  base05 = "#F0BB90", -- Default foreground, caret, delimiters, operators
  base06 = "#c19b76", -- Light foreground
  base07 = "#c9c0ae", -- Lightest foreground
  base08 = "#db6657", -- Variables, XML tags, markup link text, markup lists, diff deleted
  base09 = "#b88960", -- Orange (numbers)
  base0A = "#d89371", -- Yellow (classes)
  base0B = "#d8864a", -- Orange (strings - replaced green)
  base0C = "#9f8f82", -- Cyan (support)
  base0D = "#426A79", -- blue (functions)
  base0E = "#F7B292", -- Purple (keywords)
  base0F = "#9A4235", -- commas, brackets etc
}
M.type = "dark"
M.polish_hl = {}
return M
